export const GET_PHOTOS = `GET_PHOTOS`
export const GET_PHOTOS_SUCCESS = `GET_PHOTOS_SUCCESS`
export const GET_PHOTOS_FAILED = `GET_PHOTOS_FAILED`

export const GET_USERS = `GET_USERS`
export const GET_USERS_SUCCESS = `GET_USERS_SUCCESS`
export const GET_USERS_FAILED = `GET_USERS_FAILED`

export const GET_ALBUMS = `GET_ALBUMS`
export const GET_ALBUMS_SUCCESS = `GET_ALBUMS_SUCCESS`
export const GET_ALBUMS_FAILED = `GET_ALBUMS_FAILED`

export const SET_FILTERED_ALBUMS = `SET_FILTERED_ALBUMS`
export const CLEAR_FILTERED_ALBUMS = `CLEAR_FILTERED_ALBUMS`

export const FAVOURITE_PHOTO = `FAVOURITE_PHOTO`

export const POST_COMMENTS = `POST_COMMENTS`
export const DELETE_COMMENTS = `DELETE_COMMENTS`
